# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Vantelligence Connector
version: 1.0.30
slug: vantelligence_connector
description: MQTT Connector for devices in your camper.
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
hassio_role: default
hassio_api: true
services:
  - mqtt:need
map:
  - share:rw
full_access: true
#image: "ghcr.io/home-assistant/{arch}-addon-example"
