# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Vantelligence Connector
version: 1.0.46
slug: vantelligence_connector
description: MQTT Connector for devices in your camper.
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
host_network: true
hassio_api: true
startup: services
ingress: true
ingress_port: 8066
ports:
  8066/tcp: 8066
ports_description:
  8066/tcp: User Interface
services:
  - mqtt:need
map:
  - addon_config
  - share:rw
# full_access: true
usb: true
uart: true
udev: true
gpio: true
devicetree: true
#image: "ghcr.io/home-assistant/{arch}-addon-example"
