# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Vantelligence Connector
version: 1.0.39
slug: vantelligence_connector
description: MQTT Connector for devices in your camper.
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
hassio_api: true
startup: services
ingress: true
ingress_port: 8066
ports:
  8066/tcp: 8066
  8067/tcp: 8067
ports_description:
  8066/tcp: User Interface
  8067/tcp: Websocket
services:
  - mqtt:need
map:
  - share:rw
full_access: true
#image: "ghcr.io/home-assistant/{arch}-addon-example"
