# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Vantelligence Connector
version: 0.0.71
slug: vantelligence_connector
description: MQTT Connector for devices in your camper.
url: "https://github.com/schroeder-robert/vantelligence_connector"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
apparmor: false
host_network: true
hassio_api: true
startup: services
ingress: true
ingress_port: 8066
ports:
  8066/tcp: 8066
ports_description:
  8066/tcp: User Interface
services:
  - mqtt:need
map:
  - addon_config:rw
  - share:rw
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
devices:
  - /dev/i2c-1
devicetree: true
usb: true
uart: true
udev: true
gpio: true
audio: true
options:
  config_file: config.yaml
schema:
  config_file: str
#image: "ghcr.io/home-assistant/{arch}-addon-example"
