# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Vantelligence Connector
version: 0.0.65
slug: vantelligence_connector
description: MQTT Connector for devices in your camper.
url: "https://github.com/schroeder-robert/vantelligence_connector"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
apparmor: false
host_network: true
hassio_api: true
startup: services
ingress: true
ingress_port: 8066
ports:
  8066/tcp: 8066
ports_description:
  8066/tcp: User Interface
#image: "ghcr.io/home-assistant/{arch}-addon-example"
