support:
- homeassistant
other_devices:
- name: Bluetooth
  id: bluetooth
  class: Bluetooth
devices:
- name: Akku
  id: akku
  class: JBD_BMS
  connection:
    type: serial
    port: "/dev/ttyUSB0"
- name: Temperatursensor
  id: temperatursensor
  class: DS18B20
  interval: 30000
- name: Analogsensor
  id: analogsensor
  class: ADS1115
  connection:
    type: i2c
    bus: 1
  interval: 3000
  values:
  - name: A0
    measure: 0+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
  - name: A1
    measure: 1+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
  - name: A2
    measure: 2+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
  - name: A3
    measure: 3+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
- name: I/O Expander
  id: ioexpander
  class: MCP23017
  connection:
    type: i2c
    bus: 1
    address: 0x20
  pins:
  - name: Input0
    id: 0
    type: in
    inverted: true
  - name: Input1
    id: 1
    type: in
    inverted: true
  - name: Input2
    id: 2
    type: in
    inverted: true
  - name: Input3
    id: 3
    type: in
    inverted: true
  - name: Input4
    id: 4
    type: in
    inverted: true
  - name: Input5
    id: 5
    type: in
    inverted: true
  - name: Input6
    id: 6
    type: in
    inverted: true
  - name: Input7
    id: 7
    type: in
    inverted: true
  - name: Output0
    id: 8
    type: out
  - name: Output1
    id: 9
    type: out
  - name: Output2
    id: 10
    type: out
  - name: Output3
    id: 11
    type: out
  - name: Output4
    id: 12
    type: out
  - name: Output5
    id: 13
    type: out
  - name: Output6
    id: 14
    type: out
  - name: Output7
    id: 15
    type: out
- name: GPIO
  id: gpio
  class: GPIO
  pins:
  - name: Kanal 1+2
    id: 36
    type: out
  - name: Kanal 3+4
    id: 35
    type: out
- name: Bewegungssensor
  id: bewegungssensor
  class: MPU_6050
  connection:
    type: i2c
    bus: 1
    address: 0x69