support:
- homeassistant
devices:
- name: Temperatursensor
  id: temperatursensor
  class: DS18B20
  interval: 30000
- name: Analogsensor
  id: analogsensor
  class: ADS1115
  connection:
    type: i2c
    bus: 1
  interval: 3000
  values:
  - name: A0
    measure: 0+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
  - name: A1
    measure: 1+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
  - name: A2
    measure: 2+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
  - name: A3
    measure: 3+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
- name: GPIO
  id: gpio
  class: GPIO
  pins:
  - name: 'Relais #1'
    type: out
    id: 11
  - name: 'Relais #2'
    type: out
    id: 13
  - name: 'Relais #3'
    type: out
    id: 15
  - name: 'Relais #4'
    type: out
    id: 19
  - name: 'Relais #5'
    type: out
    id: 21
  - name: 'Relais #6'
    type: out
    id: 23
  - name: 'Relais #7'
    type: out
    id: 27
  - name: 'Relais #8'
    type: out
    id: 29