support:
- homeassistant
# other_devices:
# - name: Bluetooth
#   id: bluetooth
#   class: Bluetooth
devices:
- name: B2B-Laderegler
  id: b2b_laderegler
  class: Votronic_VCC_1212
  connection:
    type: serial
    port: /dev/serial/by-id/booster
- name: Solar-Laderegler
  id: solar_laderegler
  class: Ective_DSC
  connection:
    type: serial
    port: /dev/serial/by-id/solar
- name: Dieselheizung
  id: dieselheizung
  class: Autoterm_Air_2D
  subscribe:
    temperature_current: connector/device/luftsensor/temperature/state
  connection:
    type: serial
    port: /dev/serial/by-id/heater
- name: Akku
  id: akku
  class: JBD_BMS
  connection:
    type: serial
    port: /dev/serial/by-id/battery
- name: Temperatursensor
  id: temperatursensor
  class: DS18B20
  interval: 30000
- name: Analogsensor
  id: analogsensor
  class: ADS1115
  connection:
    type: i2c
    bus: 1
  interval: 3000
  values:
  - name: A0
    measure: 0+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
  - name: A1
    measure: 1+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
  - name: A2
    measure: 2+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
  - name: A3
    measure: 3+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
- name: I/O Expander
  id: gpio
  class: MCP23017
  connection:
    type: i2c
    bus: 1
    address: 0x20
  pins:
  - name: Input0
    id: 0
    type: in
    inverted: true
  - name: Input1
    id: 1
    type: in
    inverted: true
  - name: Input2
    id: 2
    type: in
    inverted: true
  - name: Input3
    id: 3
    type: in
    inverted: true
  - name: Input4
    id: 4
    type: in
    inverted: true
  - name: Taster hinten
    id: 5
    type: in
    inverted: true
  - name: Taster links
    id: 6
    type: in
    inverted: true
  - name: Taster richts
    id: 7
    type: in
    inverted: true
  - name: Abwasserventil auf
    id: 8
    type: out
  - name: Abwasserventil zu
    id: 9
    type: out
  - name: Wasserpumpe
    id: 10
    type: out
  - name: B2B Laderegler
    id: 11
    type: out
  - name: Soundsystem
    id: 12
    type: out
  - name: Licht
    id: 13
    type: out
  - name: Kühlschrank
    id: 14
    type: out
  - name: Dashcam
    id: 15
    type: out
- name: GPIO
  id: gpio_pi
  class: GPIO
  pins:
  - name: Kanal 1+2
    id: 36
    type: out
  - name: Kanal 3+4
    id: 35
    type: out
- name: Bewegungssensor
  id: bewegungssensor
  class: MPU_6050
  connection:
    type: i2c
    bus: 1
    address: 0x69