support:
  - homeassistant
devices:
# - name: HS-Can
#   id: hscan
#   class: Socketcan
#   connection:
#     bus: can0

# - name: Bluetooth
#   id: bluetooth
#   class: Bluetooth

# - name: PWM-Controller
#   id: pwmcontroller
#   class: PCA9685
#   connection:
#     type: i2c
#     bus: 1
#   channels:
#   - name: Licht Schiebetür links
#     id: 0
#     type: light
#   - name: Licht Laderaum
#     id: 1
#     type: light
#   - name: Licht Schiebetür rechts
#     id: 2
#     type: light
#   - name: Licht Dachluke
#     id: 3
#     type: light
#   - name: Licht5
#     id: 4
#     type: light
#   - name: Schubladenverrieglung
#     id: 14
#     min: 400
#     max: 2600
#     scale: 180
#   - name: Kühlschrankverrieglung
#     id: 15
#     min: 400
#     max: 2600
#     scale: 180

# - name: Luftsensor
#   id: luftsensor
#   class: BME280
#   connection:
#     type: i2c
#     bus: 1
# - name: Helligkeitssensor
#   id: helligkeitssensor
#   class: BH1750
#   connection:
#     type: i2c
#     bus: 1

# - name: Wechselrichter
#   id: wechselrichter
#   class: Ective_CSI
#   connection:
#     type: pins
#     power_pin: 13
#     mode_pin: 19
#     data_pin: 26

# - name: Lichtsteuerung außen
#   id: lichtsteuerung_aussen
#   class: Arduino
#   connection:
#     type: i2c
#     bus: 1
#   lights:
#   - name: 'Arbeitslicht rechts'
#   - name: 'Fernlicht links'
#   - name: 'Arbeitslicht links'
#   - name: 'Fernlicht rechts'
#   - name: 'Rücklicht links'
#   - name: 'Blinker vorne links'
#   - name: 'Blinker vorne rechts'
#     brightness: true
#   - name: 'Positionslicht rechts'
#     brightness: true
#   - name: 'Blinker hinten links'
#     brightness: true
#   - name: 'Positionslicht links'
#     brightness: true
#   - name: 'Blinker hinten rechts'
#     brightness: true
#   - name: 'Rücklicht rechts'
#     brightness: true

- name: Akku
  id: akku
  class: JBD_BMS
  connection:
    type: serial
    port: /dev/serial/by-id/battery
- name: B2B-Laderegler
  id: b2b_laderegler
  class: Votronic_VCC_1212
  connection:
    type: serial
    port: /dev/serial/by-id/booster
- name: Solar-Laderegler
  id: solar_laderegler
  class: Ective_DSC
  connection:
    type: serial
    port: /dev/serial/by-id/solar
- name: Dieselheizung
  id: dieselheizung
  class: Autoterm_Air_2D
  subscribe:
    temperature_current: connector/device/luftsensor/temperature/state
  connection:
    type: serial
    port: /dev/serial/by-id/heater

- name: Temperatursensor
  id: temperatursensor
  class: DS18B20
  interval: 30000
- name: Analogsensor
  id: analogsensor
  class: ADS1115
  connection:
    type: i2c
    bus: 1
  interval: 3000
  values:
  - name: A0
    measure: 0+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
  - name: A1
    measure: 1+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
  - name: A2
    measure: 2+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
  - name: A3
    measure: 3+GND
    min: 0
    max: 65535
    scale: 100
    unit: "%"
- name: I/O Expander
  id: gpio
  class: MCP23017
  connection:
    type: i2c
    bus: 1
    address: 0x20
  pins:
  - name: Input0
    id: 0
    type: in
    inverted: true
  - name: Input1
    id: 1
    type: in
    inverted: true
  - name: Input2
    id: 2
    type: in
    inverted: true
  - name: Input3
    id: 3
    type: in
    inverted: true
  - name: Input4
    id: 4
    type: in
    inverted: true
  - name: Taster hinten
    key: taster_hinten
    id: 5
    type: in
    inverted: true
  - name: Taster links
    key: taster_links
    id: 6
    type: in
    inverted: true
  - name: Taster rechts
    key: taster_rechts
    id: 7
    type: in
    inverted: true
  - name: Abwasserventil auf
    key: abwasserventil_auf
    id: 8
    type: out
  - name: Abwasserventil zu
    key: abwasserventil_zu
    id: 9
    type: out
  - name: Wasserpumpe
    key: wasserpumpe
    id: 10
    type: out
  - name: B2B Laderegler
    key: b2b_laderegler
    id: 11
    type: out
  - name: Soundsystem
    key: soundsystem
    id: 12
    type: out
  - name: Licht
    key: licht
    id: 13
    type: out
  - name: Kühlschrank
    key: kuehlschrank
    id: 14
    type: out
  - name: Dashcam
    key: dashcam
    id: 15
    type: out
- name: GPIO
  id: gpio_pi
  class: GPIO
  pins:
  - name: Kanal 1+2
    id: 36
    type: out
  - name: Kanal 3+4
    id: 35
    type: out
- name: Bewegungssensor
  id: bewegungssensor
  class: MPU_6050
  connection:
    type: i2c
    bus: 1
    address: 0x69
  axles:
    x:
      map: x
      flip: true
    y:
      map: z
      flip: true
    z:
      map: y
      flip: false