on:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'ok coll'
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          repository: schroeder-robert/ha-addons
          ref: main
          submodules: true
          token: ${{ secrets.PAT }}
      - run: git config --global user.name "Robert Schröder"
      - run: git config --global user.email "mail@schroeder-robert.de"
      - run: git submodule update --recursive --remote
      - run: git add -A
      - run: git commit -m "updated submodules"
      - run: git push
          
     
